# Seth Command Center - Ritual Configuration
# Weekly automated maintenance tasks

rituals:
  # Weekly doc-organizer cleanup
  - name: "Clean Project Roots"
    description: "Archive completed specs older than 14 days, maintain clean root directories"
    command: "doc-organizer run --auto-archive --days=14"
    schedule: "fridays"
    time: "09:00"
    enabled: true
    projects:
      - solienne
      - abraham-media
      - eden-academy
      - pariseye
      - vibecodings

    # Safety checks before execution
    safety_checks:
      - check_git_status: true
      - query_open_tasks: true
      - dry_run_first: true
      - add_archive_footer: true
      - never_auto_commit: true

    # Post-execution actions
    post_actions:
      - trigger: "vibecode-archivist sync"
      - log: "/docs/archive/LOG.md"
      - notify: "session-notes-append"

  # Weekly project health check
  - name: "Project Health Audit"
    description: "Generate ecosystem health report with file counts and status"
    command: "doc-organizer health --format=json"
    schedule: "fridays"
    time: "09:15"
    enabled: true
    projects:
      - solienne
      - abraham-media
      - eden-academy
      - pariseye
      - vibecodings

    post_actions:
      - output: "/Users/seth/seth-command-center/data/health-reports/latest.json"
      - dashboard_update: true

# Configuration
config:
  # Auto-archive threshold
  auto_archive_days: 14

  # Log locations per project
  log_pattern: "/docs/archive/LOG.md"

  # Archive footer template
  archive_footer: |
    ---

    _archived {date} via doc-organizer_

  # Notification settings
  notifications:
    session_notes: true
    command_center_dashboard: true

  # Safety defaults
  safety:
    always_dry_run_first: true
    require_git_clean: false  # Can proceed with uncommitted changes
    check_open_tasks: true
    never_auto_commit: true
